### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Twobit666** [MachineKillin/MSMC#2]
[0\597497] Checked
 [0] Hits
 [0] Bad
 [0] 2FA
Traceback (most recent call last):
  File "C:\Users\USER\Downloads\MSMC.py", line 322, in <module>
    Main()
  File "C:\Users\USER\Downloads\MSMC.py", line 306, in Main
    else: cuiscreen()
          ^^^^^^^^^^^
  File "C:\Users\USER\Downloads\MSMC.py", line 229, in cuiscreen
    print(f" [{vm}] Valid Mail")
               ^^
NameError: name 'vm' is not defined

**Comment by MachineKillin** [comment]
fixed
