### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by gbgdonttalk** [MachineKillin/MSMC#3]
Traceback (most recent call last):
  File "C:\Users\moshe\Downloads\MSMC-main\MSMC-main\MSMC.py", line 322, in <module>
    Main()
  File "C:\Users\moshe\Downloads\MSMC-main\MSMC-main\MSMC.py", line 304, in Main
    if screen == "'1'": cuiscreen()
  File "C:\Users\moshe\Downloads\MSMC-main\MSMC-main\MSMC.py", line 229, in cuiscreen
    print(f" [{vm}] Valid Mail")
NameError: name 'vm' is not defined

Please help

**Comment by lordarthur2** [comment]
I also got this error
Traceback (most recent call last):
File "C:\Users\moshe\Downloads\MSMC-main\MSMC-main\MSMC.py", line 322, in
Main()
File "C:\Users\moshe\Downloads\MSMC-main\MSMC-main\MSMC.py", line 304, in Main
if screen == "'1'": cuiscreen()
File "C:\Users\moshe\Downloads\MSMC-main\MSMC-main\MSMC.py", line 229, in cuiscreen
print(f" [{vm}] Valid Mail")
NameError: name 'vm' is not defined

**Comment by MachineKillin** [comment]
fixed
